
core_gamebundle_player:
  type: rest
  resource: Core\GameBundle\Controller\PlayerController

core_gamebundle_grid:
  type: rest
  resource: Core\GameBundle\Controller\GridController

core_gamebundle_gridcheck:
  type: rest
  resource: Core\GameBundle\Controller\GridCheckController
