<?php

namespace Core\GameBundle\Repository;

use Core\GameBundle\Entity\Player;
use Doctrine\ORM\EntityRepository;

/**
 * GridRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GridRepository extends \Belka\BizlayBundle\Repository\AbstractRepository
{
    public function getPlayerGrids(Player $player)
    {
    }
}
