<?php

namespace Core\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GridCheckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GridCheckRepository extends \Belka\BizlayBundle\Repository\AbstractRepository
{
}
