<?php

namespace Core\GameBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerGridRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerGridRepository extends \Belka\BizlayBundle\Repository\AbstractRepository
{
}
